version: '3'
services:
  # Node.js Application
  web:
    image: node:14
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "4000:3000"
    command: npm start

  # MySQL Database
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

